/**
 * This file was generated by Chez Scheme
 * Generated at Sat May 17 00:51:12 CST 2025
 **/

#include <cstdio>
#include <iostream>
#include <string>



bool valid_username(std::string s) {
  if (not ((((((s).length())<=(20))) && ((((s).length())>(0))) && (({
bool 
j0jni31t6u9v1se39ordqoipl7
 = true;
for (auto &j0jni31t6u9v1se39ordqoipl8 : (s))
  if (not (({
bool 
j0jni31t6u9v1se39ordqoipl9
 = false;
for (auto &j0jni31t6u9v1se39ordqoipl10 : ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_"))
  if (((j0jni31t6u9v1se39ordqoipl8)==(j0jni31t6u9v1se39ordqoipl10))) {
    j0jni31t6u9v1se39ordqoipl9 = true;
    break;
  }
j0jni31t6u9v1se39ordqoipl9
;
}))) {
    j0jni31t6u9v1se39ordqoipl7 = false;
    break;
  }
j0jni31t6u9v1se39ordqoipl7
;
})) && (({
bool 
j0jni31t6u9v1se39ordqoipl5
 = false;
for (auto &j0jni31t6u9v1se39ordqoipl6 : ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"))
  if (((s[0])==(j0jni31t6u9v1se39ordqoipl6))) {
    j0jni31t6u9v1se39ordqoipl5 = true;
    break;
  }
j0jni31t6u9v1se39ordqoipl5
;
})))))
  return false;
  return true;
}

bool valid_password(std::string s) {
  if (not ((((((s).length())<=(30))) && ((((s).length())>(0))) && (({
bool 
j0jni31t6u9v1se39ordqoipl11
 = true;
for (auto &j0jni31t6u9v1se39ordqoipl12 : (s))
  if (not (({
bool 
j0jni31t6u9v1se39ordqoipl13
 = false;
for (auto &j0jni31t6u9v1se39ordqoipl14 : ("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789|!\"#$%&´()*+,-./:;<=>?@[\\]^_`{}~"))
  if (((j0jni31t6u9v1se39ordqoipl12)==(j0jni31t6u9v1se39ordqoipl14))) {
    j0jni31t6u9v1se39ordqoipl13 = true;
    break;
  }
j0jni31t6u9v1se39ordqoipl13
;
}))) {
    j0jni31t6u9v1se39ordqoipl11 = false;
    break;
  }
j0jni31t6u9v1se39ordqoipl11
;
})))))
  return false;
  return true;
}

bool valid_mail(std::string s) {
  if (not ((((((s).length())<=(30))) && (({
bool 
j0jni31t6u9v1se39ordqoipl15
 = true;
for (auto &j0jni31t6u9v1se39ordqoipl16 : (s))
  if (not (({
bool 
j0jni31t6u9v1se39ordqoipl17
 = false;
for (auto &j0jni31t6u9v1se39ordqoipl18 : ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789@."))
  if (((j0jni31t6u9v1se39ordqoipl16)==(j0jni31t6u9v1se39ordqoipl18))) {
    j0jni31t6u9v1se39ordqoipl17 = true;
    break;
  }
j0jni31t6u9v1se39ordqoipl17
;
}))) {
    j0jni31t6u9v1se39ordqoipl15 = false;
    break;
  }
j0jni31t6u9v1se39ordqoipl15
;
})))))
  return false;
  return true;
}

bool valid_privilege(std::string s) {
  if (not (((({
bool 
j0jni31t6u9v1se39ordqoipl19
 = true;
for (auto &j0jni31t6u9v1se39ordqoipl20 : (s))
  if (not (({
bool 
j0jni31t6u9v1se39ordqoipl21
 = false;
for (auto &j0jni31t6u9v1se39ordqoipl22 : ("0123456789"))
  if (((j0jni31t6u9v1se39ordqoipl20)==(j0jni31t6u9v1se39ordqoipl22))) {
    j0jni31t6u9v1se39ordqoipl21 = true;
    break;
  }
j0jni31t6u9v1se39ordqoipl21
;
}))) {
    j0jni31t6u9v1se39ordqoipl19 = false;
    break;
  }
j0jni31t6u9v1se39ordqoipl19
;
})) && ((((((s).length())==(1))) || (s == "10"))))))
  return false;
  return true;
}

int main() {
  std::string s;
  std::cin >> s;
  std::cout << valid_username(s) << std::endl;
  std::cout << valid_password(s) << std::endl;
  std::cout << valid_mail(s) << std::endl;
  return 0;
}

