/**
 * This file was generated by Chez Scheme
 * Generated at "Sat May 17 11:23:41 2025"
 **/

#include <cstdio>
#include <iostream>
#include <string>

bool valid_username(std::string s) {
  if (not ((((((s).length())<=(20))) && ((((s).length())>(0))) && (({
bool 
flag21
 = true;
for (auto &tmpvar22 : (s))
  if (not (({
bool 
flag23
 = false;
for (auto &tmpvar24 : ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_"))
  if (((tmpvar22)==(tmpvar24))) {
    flag23 = true;
    break;
  }
flag23
;
}))) {
    flag21 = false;
    break;
  }
flag21
;
})) && (({
bool 
flag19
 = false;
for (auto &tmpvar20 : ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"))
  if (((s[0])==(tmpvar20))) {
    flag19 = true;
    break;
  }
flag19
;
})))))
  return false;
  return true;
}

bool valid_password(std::string s) {
  if (not ((((((s).length())<=(30))) && ((((s).length())>(0))) && (({
bool 
flag25
 = true;
for (auto &tmpvar26 : (s))
  if (not (({
bool 
flag27
 = false;
for (auto &tmpvar28 : ("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789|!\"#$%&´()*+,-./:;<=>?@[\\]^_`{}~"))
  if (((tmpvar26)==(tmpvar28))) {
    flag27 = true;
    break;
  }
flag27
;
}))) {
    flag25 = false;
    break;
  }
flag25
;
})))))
  return false;
  return true;
}

bool valid_mail(std::string s) {
  if (not ((((((s).length())<=(30))) && (({
bool 
flag29
 = true;
for (auto &tmpvar30 : (s))
  if (not (({
bool 
flag31
 = false;
for (auto &tmpvar32 : ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789@."))
  if (((tmpvar30)==(tmpvar32))) {
    flag31 = true;
    break;
  }
flag31
;
}))) {
    flag29 = false;
    break;
  }
flag29
;
})))))
  return false;
  return true;
}

bool valid_privilege(std::string s) {
  if (not (((({
bool 
flag33
 = true;
for (auto &tmpvar34 : (s))
  if (not (({
bool 
flag35
 = false;
for (auto &tmpvar36 : ("0123456789"))
  if (((tmpvar34)==(tmpvar36))) {
    flag35 = true;
    break;
  }
flag35
;
}))) {
    flag33 = false;
    break;
  }
flag33
;
})) && ((((((s).length())==(1))) || (s == "10"))))))
  return false;
  return true;
}

int main() {
  std::string s;
  std::cin >> s;
  // for (auto x : "123")
  //   printf("%d\n", (int)x);
  std::cout << valid_username(s) << std::endl;
  std::cout << valid_password(s) << std::endl;
  std::cout << valid_mail(s) << std::endl;
  return 0;
}
