/**
 * This file was generated by Chez Scheme
 * Generated at "Wed May 21 21:53:56 2025"
 *
 * 2025 © Coffish
 **/

#include <cstdio>
#include <iostream>
#include <string>

bool valid_username(std::string s) {
  if (not((((((s).length()) <= (20))) && ((((s).length()) > (0))) && (({
             bool flag3 = true;
             for (auto &tmpvar4 : (s))
               if (not(({
                     bool flag5 = false;
                     for (auto &tmpvar6 : ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghi"
                                           "jklmnopqrstuvwxyz0123456789_"))
                       if (((tmpvar4) == (tmpvar6))) {
                         flag5 = true;
                         break;
                       }
                     flag5;
                   }))) {
                 flag3 = false;
                 break;
               }
             flag3;
           })) &&
           (({
             bool flag1 = false;
             for (auto &tmpvar2 :
                  ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"))
               if (((s[0]) == (tmpvar2))) {
                 flag1 = true;
                 break;
               }
             flag1;
           })))))
    return false;
  return true;
}

bool valid_password(std::string s) {
  if (not((((((s).length()) <= (30))) && ((((s).length()) > (0))) && (({
             bool flag7 = true;
             for (auto &tmpvar8 : (s))
               if (not(({
                     bool flag9 = false;
                     for (auto &tmpvar10 :
                          ("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXY"
                           "Z0123456789|!\"#$%&´()*+,-./:;<=>?@[\\]^_`{}~"))
                       if (((tmpvar8) == (tmpvar10))) {
                         flag9 = true;
                         break;
                       }
                     flag9;
                   }))) {
                 flag7 = false;
                 break;
               }
             flag7;
           })))))
    return false;
  return true;
}

bool valid_mail(std::string s) {
  if (not((((((s).length()) <= (30))) && (({
             bool flag11 = true;
             for (auto &tmpvar12 : (s))
               if (not(({
                     bool flag13 = false;
                     for (auto &tmpvar14 : ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefgh"
                                            "ijklmnopqrstuvwxyz0123456789@."))
                       if (((tmpvar12) == (tmpvar14))) {
                         flag13 = true;
                         break;
                       }
                     flag13;
                   }))) {
                 flag11 = false;
                 break;
               }
             flag11;
           })))))
    return false;
  return true;
}

bool valid_privilege(std::string s) {
  if (not(((({
             bool flag15 = true;
             for (auto &tmpvar16 : (s))
               if (not(({
                     bool flag17 = false;
                     for (auto &tmpvar18 : ("0123456789"))
                       if (((tmpvar16) == (tmpvar18))) {
                         flag17 = true;
                         break;
                       }
                     flag17;
                   }))) {
                 flag15 = false;
                 break;
               }
             flag15;
           })) &&
           ((((((s).length()) == (1))) || (s == "10"))))))
    return false;
  return true;
}

int main() {
  std::string s;
  std::cin >> s;
  std::cout << valid_username(s) << std::endl;
  std::cout << valid_password(s) << std::endl;
  std::cout << valid_mail(s) << std::endl;
  return 0;
}
